<a href="https://colab.research.google.com/github/mandalsantanu16092002/Python-learning/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

A Series is a one-dimensional labeled array capable of holding any data type. The axis labels are collectively called the index.

In [3]:
#Creating Series
#There are multiple ways to create a pandas Series:

labels = ['a', 'b', 'c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {'a':10,'b':20,'c':30}

In [4]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [5]:
pd.Series(my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [6]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [7]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64


**Creating a DataFrame**

In [8]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [9]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [10]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
column = ['Name', 'Age', 'City', 'Salary']
df2.columns = column  #df2 = pd.DataFrame(data_list,columns =columns)
df2.head() #df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [11]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [12]:
print(df2)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

**Selection and Indexing of Columns**

In [13]:
df2[["Name","City"]]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [14]:
df2["City"]

0    New York
1       Paris
2      Berlin
3      London
Name: City, dtype: object

**Creating a new column**

In [15]:
df2["Designation"] = ["Doctor","Eng.","Doctor","Eng."]
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

**Removing Columns**  ---> AXIS 0 FOR HORIZONTAL AND AXIS 1 FOR VERTICAL

In [16]:
df2.drop(0,axis = 0) #ram thake delete hoyna

    Name  Age    City  Salary Designation
1   Anna   34   Paris   70000        Eng.
2  Peter   29  Berlin   62000      Doctor
3  Linda   42  London   85000        Eng.

In [17]:
df2  #tai abar chole asbe

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

In [18]:
df2.drop('Designation', axis=1)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [19]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

In [20]:
df2.drop('Designation', axis=1, inplace=True)   #permanently delete

In [21]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

**Selecting Rows**

In [22]:
df2.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [23]:
df2.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [24]:
df.iloc[3]  #index location same as loc

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

In [25]:
df2.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [26]:
df2.iloc[[2,3]][["Name","Age"]]

    Name  Age
2  Peter   29
3  Linda   42

**conditional selection**

In [27]:
df2[df2["Age"]>30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [28]:
df2[(df2["Age"]>30) & (df2["Salary"]>70000)]

    Name  Age    City  Salary
3  Linda   42  London   85000

**MISSING DATA**

In [29]:
#FINDING MISSING DATA

data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)

In [30]:
df  #NaN = not a number -> Null values

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [31]:
df.isna()  #if it is a null value == True, else false

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

.sum(): When applied to the boolean DataFrame returned by df.isna(), the sum() method counts the True values in each column. Since True is treated as 1 and False as 0 in numerical operations, summing the boolean values effectively counts the number of missing values in each column.

In [32]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [33]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

**Removing Missing Data**

In [35]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [36]:
df.dropna(thresh=3) #rows a non null value 3 ta thakbe

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

**Filling the missing data**

In [38]:
df.fillna(0)  #sob NaN = 0 hoye jabe

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [39]:
values = {'A':0,'B':100,"C":300,'D':400}
df.fillna(value=values)  #column wise sob A column ar NaN te 0, sob B column ar NaN te 100

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

In [40]:
df.fillna(df.mean())  # Column A te 1+2+4+5/4 = 3 in NaN, Column C te 1+2+3/3 = 2 in NaN, Column D te 1+5/2 = 3 in NaN

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

**Merging 2 dataframes**